### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by cmcnicholas** [KeesCBakker/Strongly-Typed-Events-for-TypeScript#269] opened 2021-08-06 17:05 UTC
When bundled with Rollup (using vite https://vitejs.dev/) there is a circular reference on `ste-core`'s `DispatcherBase`

## Expected Behavior

Should bundle correctly.

## Current Behavior

![image](https://user-images.githubusercontent.com/41394833/128546030-228bfbbf-3978-4436-aee7-2abc68063cd4.png)

## Context (Environment)

TypeScript with Vue using Vite.

**Comment by KeesCBakker** [comment] 2021-08-09 05:54
Cool I'll look into it. What version are you using?

**Comment by KeesCBakker** [comment] 2021-08-09 06:19
I'm not familiar with Vite. Can you make a small setup that reproduces the issue?

**Comment by cmcnicholas** [comment] 2021-08-09 09:11
https://github.com/cmcnicholas/ste-simple-events-circular-ref

you can run `npm run build` then `npm run serve` to test, check the console, this is pretty much an absolute minimum viable repo

**Comment by cmcnicholas** [comment] 2021-08-09 09:11
> Cool I'll look into it. What version are you using?

this is latest version

**Comment by AndiRudi** [comment] 2021-10-17 10:50
I have the same issue in a svelte based setup with rollup. When I do `import { EventDispatcher } from "strongly-typed-events";` and run the application it reports 
```
PromiseDispatcherBase.js:16 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at PromiseDispatcherBase.js:16
    at main.ts:8
(anonymous) @ PromiseDispatcherBase.js:16
(anonymous) @ main.ts:8
```

**Comment by KeesCBakker** [comment] 2021-11-10 09:19
I'm not sure what we can do to fix this problem. I love to do a major version update if we have a fix.

**Comment by KeesCBakker** [comment] 2021-11-10 09:41
@cmcnicholas, looks like the browser version does not have this problem: https://cdn.jsdelivr.net/npm/ste-browser@latest/dist/strongly-typed-events.min.js

Wondering what's different. Can you check what https://www.npmjs.com/package/ste-browser does for you?

**Comment by KeesCBakker** [comment] 2022-03-23 09:27
Should be fixed now since version `3.0.1`, can you please check?

**Comment by KeesCBakker** [comment] 2022-03-23 09:28
@silveredgold seems to have found a fix.

**Comment by KeesCBakker** [comment] 2022-05-02 11:50
I'm closing the issue due to inactivity.

**Closed by KeesCBakker** 2022-05-02 11:50 UTC
Labels: under investigation
